#pragma once

#define SHADER_BINDPOINT_CAMERA_VP 0
#define SHADER_BINDPOINT_ACCUMULATION_PARTITION 1
#define SHADER_BINDPOINT_WINDFIELD_PARTITION 2

#define SSBO_MAX_INT_ARRAY 250000

//#define ENABLE_BENCHMARK

#ifdef ENABLE_BENCHMARK
#define COLLISION_BENCHMARK_ITERATIONS 1
#endif

